### ISSUE TITLE
Migrate to High-Replication Datastore

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot-old#138]
See https://developers.google.com/appengine/docs/adminconsole/migration.  We need to migrate from Master/Slave to High-Replication for the reviews app.  Do we use the datastore?

**Comment by asmeurer** [comment]
I started work on this. The new app is `sympy-reviews` (I'll give you access if you want to play around with it). I deployed the app, but right now, it gives a 500, and the log stays

``` pytb
Traceback (most recent call last):
  File "/base/data/home/apps/s~sympy-reviews/6.367212462091732030/main.py", line 1, in <module>
    from app.main import main
  File "/base/data/home/apps/s~sympy-reviews/6.367212462091732030/app/main.py", line 9, in <module>
    from google.appengine.dist import use_library
ImportError: No module named dist
```

**Comment by asmeurer** [comment]
Also, @certik, how do you manually populate the pull requests?
