### ISSUE TITLE
TypeError: not all arguments converted during string formatting with 504

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot-old#66]
``` pytb
$./sympy-bot review 731
> Using /Users/aaronmeurer/.sympy/sympy-bot.conf
> Checking username and password ...
>     OK.
> Working directory: /var/folders/wc/dppcpmxs1tlb36nqcw853wkm0000gn/T/sympy-bot-tmpso0Ui5
> Reviewing pull request #731
> Pull request info:
>     Author: "Bilal Akhtar" <bilalakhtar@ubuntu.com>
>     Repository: https://github.com/bilalakhtar/sympy
>     Branch: master
> Cloning sympy/sympy master
Cloning into 'sympy'...
> Testing...
Running tests with the following setup:
master_repo_url = https://github.com/sympy/sympy.git
pull_request_repo_url = https://github.com/bilalakhtar/sympy
pull_request_branch = master
master_repo_path = /var/folders/wc/dppcpmxs1tlb36nqcw853wkm0000gn/T/sympy-bot-tmpso0Ui5/sympy
test_command = setup.py test
interpreter = python2.5
cd /var/folders/wc/dppcpmxs1tlb36nqcw853wkm0000gn/T/sympy-bot-tmpso0Ui5/sympy; git fetch https://github.com/bilalakhtar/sympy master:test
error: The requested URL returned error: 504 while accessing https://github.com/bilalakhtar/sympy/info/refs
fatal: HTTP request failed
Done.

View log at: /var/folders/wc/dppcpmxs1tlb36nqcw853wkm0000gn/T/sympy-bot-tmpso0Ui5/out/log
> Uploading test results
> Uploaded report at: http://reviews.sympy.org/report/agZzeW1weTNyDAsSBFRhc2sY_sEEDA
Traceback (most recent call last):
  File "./sympy-bot", line 244, in <module>
    main()
  File "./sympy-bot", line 96, in main
    review(n, options)
  File "./sympy-bot", line 229, in review
    user, config)
  File "./sympy-bot", line 122, in formulate_review
    summary = """Could not fetch the branch.  Please run the sympy-bot tests again.""" % atuser
TypeError: not all arguments converted during string formatting
```

**Comment by goodok** [comment]
This was corrected in PR 65, but not as separated commit, so new one:
https://github.com/sympy/sympy-bot/pull/67

**Comment by certik** [comment]
I think that this is fixed.
