### ISSUE TITLE
master_hash missing on unmergeable PRs causing a crash

### ISSUE THREAD

**Issue by Krastanov** [sympy/sympy-bot-old#75]
```
Auto-merging doc/src/modules/assumptions/index.txt
Auto-merging sympy/core/expr.py
CONFLICT (content): Merge conflict in sympy/core/expr.py
Automatic merge failed; fix conflicts and then commit the result.
Done.

View log at: /tmp/sympy-bot-tmpmSdoXH/out/log
Traceback (most recent call last):
  File "./sympy-bot", line 279, in <module>
    main()
  File "./sympy-bot", line 97, in main
    review(n, options)
  File "./sympy-bot", line 244, in review
    master_hash = result["master_hash"]
KeyError: 'master_hash'
```

**Comment by certik** [comment]
@Krastanov, can you please review the pull request fixing this bug (#76)?

**Comment by Krastanov** [comment]
I'll check it this evening (European evening).

2011/12/12 Ondřej Čertík <
reply@reply.github.com
