### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot-old#95]
I've been getting this error a lot lately.  Rerunning the bot enough times makes it work.

``` pytb
/Users/aaronmeurer/.sympy/sympy-bot.conf
> Using /Users/aaronmeurer/.sympy/sympy-bot.conf
> Checking username and password ...
>     OK.
> Working directory: /var/folders/wc/dppcpmxs1tlb36nqcw853wkm0000gn/T/sympy-bot-tmp3p_4R4
Traceback (most recent call last):
  File "./sympy-bot", line 337, in <module>
    main()
  File "./sympy-bot", line 130, in main
    review(n, options, username, password)
  File "./sympy-bot", line 258, in review
    pull = github_get_pull_request(config.repository, n)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy-bot/utils.py", line 121, in github_get_pull_request
    data = json.load(urlopen(url % n))
  File "/sw/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/sw/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/sw/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/sw/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by asmeurer** [comment]
Haven't seen this in a while.
